^https:\/\/xiaominweb\.ccbft\.com\/smartoffice\/attendservice\/appattendservice\/appattend\/v3\/addAppAttendRecord url script-request-body https://raw.githubusercontent.com/chenglich/qxrewrite/main/xm/attend_modify.js

hostname = xiaominweb.ccbft.com
